# Generated by Django 3.2.7 on 2021-10-02 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20210917_1917'),
        ('cart', '0007_auto_20210915_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='active',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='cart_item',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cart_fk', to='cart.cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='product_fk', to='product.product'),
        ),
    ]
