# Generated by Django 3.2.7 on 2021-09-03 23:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('country', models.CharField(blank=True, max_length=30, null=True, verbose_name='کشور دفتر مرکزی')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='شهر دفتر مرکزی')),
                ('phone_number', models.IntegerField(blank=True, null=True, verbose_name='تلفن دفتر مرکزی')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل دفتر مرکزی')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='دسته')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='زیر مجموعه')),
            ],
            options={
                'verbose_name': 'دسته بندی ها',
                'verbose_name_plural': 'گروه بندی',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('upc', models.PositiveBigIntegerField(help_text='بارکد ۱۲ رقمی')),
                ('count', models.IntegerField(default=0, verbose_name='تعداد')),
                ('status', models.CharField(choices=[('N', 'Not_Exist'), ('A', 'Active'), ('W', 'Will_not_be_produced'), ('O', 'Ordered')], default='N', max_length=1)),
                ('size', models.CharField(blank=True, max_length=30, null=True)),
                ('wat', models.IntegerField(blank=True, null=True, verbose_name='wat')),
                ('voltage', models.IntegerField(blank=True, null=True, verbose_name='Voltage')),
                ('discription', models.TextField(blank=True, max_length=30, null=True, verbose_name='توضیحات اضافی')),
                ('price', models.FloatField(default=0, help_text='﷼')),
                ('set_time', models.DateTimeField(auto_now_add=True)),
                ('date_start', models.DateTimeField(default=None, verbose_name='زمان شروع تخفیف')),
                ('date_end', models.DateTimeField(default=None, verbose_name='زمان پایان تخفیف')),
                ('Temporary_price', models.FloatField(verbose_name='قیمت مموقت')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.brand')),
                ('cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category')),
            ],
            options={
                'verbose_name': 'محصولات',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, default=None, null=True, upload_to='Project_Pictures', validators=[django.core.validators.validate_image_file_extension])),
                ('discription', models.CharField(default=None, max_length=100)),
                ('video_description', models.FileField(blank=True, null=True, upload_to='hand_product_video/')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('image_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
