# Generated by Django 3.2.7 on 2021-09-04 19:22

import django.core.validators
from django.db import migrations, models
import utils.models_utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210904_0026'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='discription',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='media',
            name='video_description',
        ),
        migrations.AddField(
            model_name='media',
            name='video_product',
            field=models.FileField(blank=True, null=True, upload_to=utils.models_utils.model_image_directory_path),
        ),
        migrations.AddField(
            model_name='product',
            name='catalog',
            field=models.FileField(default=None, upload_to=utils.models_utils.model_image_directory_path, verbose_name='کاتالوگ'),
        ),
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.FloatField(blank=True, null=True, verbose_name='قیمت محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ManyToManyField(to='users.Supplier'),
        ),
        migrations.AlterField(
            model_name='media',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=utils.models_utils.model_image_directory_path, validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='product',
            name='Temporary_price',
            field=models.FloatField(blank=True, null=True, verbose_name='قیمت مموقت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع تخفیف'),
        ),
    ]
