# Generated by Django 3.2.7 on 2021-09-04 20:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utils.models_utils


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210904_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='picture',
        ),
        migrations.AddField(
            model_name='media',
            name='product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='media',
            name='image_product',
            field=models.ImageField(blank=True, null=True, upload_to=utils.models_utils.model_image_directory_path, validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
