# Generated by Django 3.2.7 on 2021-09-15 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210915_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='product.product'),
        ),
    ]
