# Generated by Django 3.2.7 on 2021-09-15 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_media_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_acrive',
            new_name='is_archive',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='att_fk',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='voltage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wat',
        ),
        migrations.AddField(
            model_name='attribute',
            name='datetime_value',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='float_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='timr_value',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='Attributekey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('unit', models.CharField(default=None, max_length=50, unique=True)),
                ('is_numeric', models.BooleanField()),
                ('is_float', models.BooleanField()),
                ('is_string', models.BooleanField()),
                ('is_time', models.BooleanField()),
                ('is_datetime', models.BooleanField()),
                ('att_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.attributekey')),
            ],
        ),
        migrations.AddField(
            model_name='attribute',
            name='attrs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attrval', to='product.attributekey'),
            preserve_default=False,
        ),
    ]
