# Generated by Django 3.2.7 on 2021-09-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210915_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributekey',
            name='unit',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
    ]
