# Generated by Django 3.2.7 on 2021-09-15 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_attributekey_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='timr_value',
            new_name='time_value',
        ),
    ]
