# Generated by Django 3.2.7 on 2021-09-17 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_rename_timr_value_attribute_time_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attrproduct', to='product.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attribute',
            name='datetime_value',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='time_value',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attributekey',
            name='att_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attkey', to='product.attributekey'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='filed',
        ),
        migrations.AddField(
            model_name='product',
            name='filed',
            field=models.ManyToManyField(blank=True, through='product.Attribute', to='product.Attributekey', verbose_name='Extra Filed'),
        ),
    ]
