# Generated by Django 3.2.7 on 2021-09-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210917_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='upc',
            field=models.PositiveBigIntegerField(blank=True, help_text='بارکد ۱۲ رقمی', null=True),
        ),
    ]
