# Generated by Django 3.2.7 on 2021-10-04 05:33

import django.core.validators
from django.db import migrations, models
import utils.models_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('text', models.TextField()),
                ('imgae', models.ImageField(blank=True, default=None, null=True, upload_to=utils.models_utils.model_image_directory_path, validators=[django.core.validators.validate_image_file_extension])),
            ],
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
            ],
        ),
    ]
