# Generated by Django 3.2.7 on 2021-09-03 23:36

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.models_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=11)),
                ('first_name', models.CharField(max_length=250, verbose_name='نام')),
                ('last_name', models.CharField(max_length=250, verbose_name='نام خانوادگی')),
                ('age', models.IntegerField(verbose_name='سن')),
                ('image', models.ImageField(upload_to=utils.models_utils.model_image_directory_path)),
                ('address', models.CharField(max_length=500, verbose_name='نشانی')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'karbaran',
                'verbose_name_plural': 'karbaran',
            },
        ),
        migrations.CreateModel(
            name='Regular',
            fields=[
                ('ouruser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.ouruser')),
                ('code_meli', models.PositiveIntegerField(max_length=10, verbose_name='کدملی')),
                ('gender', models.CharField(choices=[('مرد', 'man'), ('زن', 'woman'), ('دیگر', 'other')], max_length=5, verbose_name='جنسیت')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.ouruser',),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('ouruser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.ouruser')),
                ('staff_number', models.PositiveIntegerField(max_length=10, verbose_name='کد کارمندی')),
                ('staff_duty', models.PositiveIntegerField(max_length=10, verbose_name='مقام')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.ouruser',),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('ouruser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.ouruser')),
                ('open_working_hour', models.TimeField(verbose_name='زمان شروع کار در روز')),
                ('close_working_hour', models.TimeField(verbose_name='زمان پایان کار در روز')),
                ('EXCEL', models.FileField(upload_to=utils.models_utils.model_image_directory_path, verbose_name='فایل اکسل محصولات خود را در اینجا باز گذاری کنید ')),
                ('bank_shaba', models.PositiveIntegerField(max_length=16, verbose_name='شماره شبا کارت بانکی خود را وارد کنید')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.ouruser',),
        ),
    ]
