# Generated by Django 3.2.7 on 2021-09-03 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='company_name',
            field=models.CharField(default='فروشنده حقوقی', max_length=200),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_duty',
            field=models.CharField(max_length=10, verbose_name='مقام'),
        ),
    ]
