# Generated by Django 3.2.7 on 2021-09-04 00:22

from django.db import migrations, models
import utils.models_utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210904_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ouruser',
            name='username',
        ),
        migrations.AlterField(
            model_name='ouruser',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='نشانی'),
        ),
        migrations.AlterField(
            model_name='ouruser',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='سن'),
        ),
        migrations.AlterField(
            model_name='ouruser',
            name='first_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='ouruser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.models_utils.model_image_directory_path),
        ),
        migrations.AlterField(
            model_name='ouruser',
            name='last_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='نام خانوادگی'),
        ),
    ]
