# Generated by Django 3.2.7 on 2021-09-04 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210904_0022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regular',
            options={'verbose_name': 'Regular', 'verbose_name_plural': 'Regular'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Staff', 'verbose_name_plural': 'Staff'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Supplier', 'verbose_name_plural': 'Supplier'},
        ),
    ]
