# Generated by Django 3.2.7 on 2021-09-04 19:40

from django.db import migrations, models
import utils.models_utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210904_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='EXCEL',
            field=models.FileField(blank=True, null=True, upload_to=utils.models_utils.model_image_directory_path, verbose_name='فایل اکسل محصولات خود را در اینجا باز گذاری کنید '),
        ),
    ]
