# Generated by Django 3.2.7 on 2021-09-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_supplier_excel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regular',
            name='code_meli',
            field=models.IntegerField(verbose_name='کدملی'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_duty',
            field=models.CharField(max_length=50, verbose_name='مقام'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_number',
            field=models.IntegerField(verbose_name='کد کارمندی'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='bank_shaba',
            field=models.IntegerField(verbose_name='شماره شبا کارت بانکی خود را وارد کنید'),
        ),
    ]
