# Generated by Django 3.2.7 on 2021-09-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210909_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouruser',
            name='username',
            field=models.CharField(default='defult', max_length=50),
        ),
    ]
