# Generated by Django 3.2.7 on 2021-09-12 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_ouruser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ouruser',
            old_name='image',
            new_name='avatar',
        ),
    ]
