# Generated by Django 3.2.7 on 2021-09-13 20:16

from django.db import migrations, models
import utils.models_utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_image_ouruser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouruser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=utils.models_utils.model_supplier_directory_path),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='EXCEL',
            field=models.FileField(blank=True, null=True, upload_to=utils.models_utils.model_supplier_directory_path, verbose_name='فایل اکسل محصولات خود را در اینجا باز گذاری کنید '),
        ),
    ]
